### ISSUE TITLE
Sun's Lens Flare Off-Centered 16:9 Widescreen

### ISSUE THREAD

**Issue by toxicdumbster** [sonicretro/sadx-mod-loader#18]
Dreamcast~
![untitled02](https://user-images.githubusercontent.com/30303512/28394498-5bd767b8-6cbb-11e7-8e37-1685717974a8.png)

vs

PC~
![untitled00](https://user-images.githubusercontent.com/30303512/28394511-76a67fc0-6cbb-11e7-84b8-5c927d815cb5.png)

I can change lens flare direction, that is…whenever I play around with the window size.
![untitled01](https://user-images.githubusercontent.com/30303512/28394564-e70ac3b6-6cbb-11e7-86a3-8d906ab8c690.png)

**Comment by SonicFreak94** [comment]
Hm, the logic might need to be updated to account for widescreen resolutions. Thanks for the report.

**Comment by MainMemory** [comment]
I'm pretty sure that's lens flare, not god ray.

**Comment by toxicdumbster** [comment]
Whatever.

**Comment by Rayray-Alcard** [comment]
` MainMemory commented 20 hours ago: I'm pretty sure that's lens flare, not god ray.`

Well there is kinda both being shown in those pictures. I say this because sun texture itself pop out like a shining star. When blending with clouds, it looks like some shining beams of light that burst through clouds are at display like crepuscular rays.
![28394498-5bd767b8-6cbb-11e7-8e37-1685717974a8](https://user-images.githubusercontent.com/27602092/28442554-d4fe785c-6d7e-11e7-8aa7-fc672ab849a2.png)
^Of course, there is no such real effect in this game. This very part of the skybox cloud texture just happened to be designed that way for the sun.

Another thing is I find it most odd how there are two suns in this particular act. If you take a good look around the sky, you see another sun isolated from clouds.

Not to mention the oddity how the sun and its lens flare can be seen through walls.
![untitled](https://user-images.githubusercontent.com/27602092/28444286-1641b7ba-6d8a-11e7-960a-20003a392fca.png)

These are normal behaviors. Not that this talk has anything to do with what the original poster referred to exactly—just noting on what is being shown in his pictures and differences between crepuscular rays aka god rays and lens flare, for those who’re confused. Lens flare are the rainbow-ish/blue/green/red colored circles you see when you get a glimpse of the sun throughout few areas of the stage.

**Comment by SonicFreak94** [comment]
Fixed. It was using hard-coded screen dimensions.
