### ISSUE TITLE
Global config option to start the game in Japanese

### ISSUE THREAD

**Issue by PiKeyAr** [sonicretro/sadx-mod-loader#42]
At the moment the game defaults to English until a save with Japanese language settings is loaded. Adding an option to specify the game's default language setting would be cool for mods because:
1) It will allow to get rid of the "Sega/Sonic Team voice language" setting in SADXFE and Dreamcast DLCs. The game doesn't know which language to play the voices in so we had to add this option, which doesn't respect the game's language setting. Having it consistent with the global setting would be nice.
2) It will allow to use several things that previously were unused, such as the Japanese "Press Enter" prompt on the title screen. I would also use it in the DC mod to load the Japanese title screen on startup, which at the moment shows up only when the file with Japanese text settings is loaded.

**Comment by cheatfreak47** [comment]
This would also be a good opportunity to make the game load RE-JP.mpg instead of RE-US.mpg as well, since that's another unused file.

IIRC, MainMemory said that there's no references to that file in the game at all, so if this is added, making the game actually load that file when "Global Language" is set to Japanese would be a good idea.

**Comment by PiKeyAr** [comment]
Fixed in [this](https://github.com/sonicretro/sadx-mod-loader/pull/70) pull request.
