### ISSUE TITLE
Game instantly closes when starting

### ISSUE THREAD

**Issue by MailBoxSNES** [sonicretro/sadx-mod-loader#50]
when ever i start up the SADX With the mod loader installed the game exits as soon as the window opens

**Comment by MainMemory** [comment]
That usually indicates a problem initializing Direct3D. Try setting the game to windowed mode in the config editor, enable Windowed Fullscreen, or use the drop-down menu to set the resolution to Native.

**Comment by MailBoxSNES** [comment]
i already tried messing with the options and nothing worked

**Comment by MainMemory** [comment]
Does it happen even with no mods enabled?

**Comment by MailBoxSNES** [comment]
yes

**Comment by PiKeyAr** [comment]
The only time I was able to reproduce this was when I set DPI scale above 100%. Forcing windowed mode and/or borderless fullscreen usually causes this in combination with DPI scaling.

If you use Windows 10, right click sonic.exe, open properties and set DPI scaling mode to "Application" instead of "System". It may also be a good idea to disable "Fullscreen Optimizations" in the same tab. In older versions of Windows there's a checkbox "Disable scaling on High DPI displays" instead. You need to keep it checked for sonic.exe.
If you use SADX Mod Installer, it should add these fixes to registry automatically.

**Comment by MailBoxSNES** [comment]
alright it seems to be working now. but when i load the lantern engine it shows a white screen for a few seconds then it closes

**Comment by FateForWindows** [comment]
Run dxdiag and take a screenshot of the display tab.

**Comment by MailBoxSNES** [comment]
While I was running the game my computer crashed with a Video_TDR_Failure

**Comment by FateForWindows** [comment]
Like I said, can you please open dxdiag and take a screenshot of the graphics tab?

**Comment by MailBoxSNES** [comment]
Ok I will do that when I get the time

**Comment by MailBoxSNES** [comment]
![image](https://user-images.githubusercontent.com/33904535/53700422-309b2580-3dc0-11e9-91a4-1ca11933fcfd.png)
![image](https://user-images.githubusercontent.com/33904535/53700426-3e50ab00-3dc0-11e9-99d8-d680a0273f8b.png)

**Comment by MailBoxSNES** [comment]
anyone still here?

**Comment by cheatfreak47** [comment]
Everyone is still here we just don't know exactly what to do. If you wanna add me on discord I could try and help you troubleshoot, I guess.
CheatFreak#3799

**Comment by PiKeyAr** [comment]
Well, the original issue
> when ever i start up the SADX With the mod loader installed the game exits as soon as the window opens
appears to have been resolved?

Neither the TDR error nor the crash with Lantern Engine are Mod Loader issues.

If the game doesn't start up specifically with Lantern Engine enabled, but starts up with other mods, make sure your DirectX is up to date and you're using [the latest release version of Lantern Engine](https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/Setup/data/sadx-dc-lighting.7z) with a matching version of the [d3d8.dll shim](https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/Setup/data/d3d8.dll). 
The TDR error is a crash related to the graphics driver. I've been running SADX on the same GPU (with a slightly newer 22.20.16.4815 driver though) and it's been working fine so far. The TDR error may be caused by overheating or bad overclock. Also, is this the only GPU on your computer, or is there a dedicated GPU with a system like nVIDIA Optimus? It might be the nVIDIA GPU crashing if it's there. If you ran into this while playing SADX, it's likely affecting other games too. Make sure your system is stable and the drivers are up to date.
There isn't much beyond this to suggest, unfortunately.

**Comment by FateForWindows** [comment]
His system has no dedicated GPU, just the integrated one.
